name: kjk
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3704516035504639
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.375
  lightness: 0.015237958868965507
  saturation: 0.2995273391716182
  rhythmicContrast: 0.03765444364398718
purpose: []
